config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}

  root 'home#index'

  resources :award_ceremonies, only: :index
  resources :entries, only: [:show, :edit, :update]
  resources :pools, only: [:show, :index] do
    resources :entries, only: [:new, :create]
  end

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  belongs_to :award_ceremony
  has_many :entries
  has_many :categories, through: :award_ceremony

  delegate :name, to: :award_ceremony, prefix: true
  delegate :locks_at, to: :award_ceremony

  def locked?
    Time.current >= locks_at
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  def index
    if current_user.present?
      @pools = current_user.pools
    else
      redirect_to root_path
    end
  end
  def show
    @pool = Pool.find(params[:id])
  end
end

app/views/pools/index.html.erb
<div>
  <h3>Pools</h3>
  <table class="minimal-table">
    <thead>
      <th>Pools</th>
      <th></th>
    </thead>
    <tbody>
      <% @pools.each do |p| %>
        <tr>
          <td><%= p.award_ceremony_name %></td>
          <td>
            <%= link_to 'View Pool', pool_path(id: p.id) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pools/show.html.erb
<div>
  <h3>Pool</h3>
  <% if !@pool.entries.map(&:user).include? current_user %>
    <%= link_to 'Join Pool', new_pool_entry_path(pool_id: @pool.id) %>
  <% end %>
  <table class="minimal-table">
    <thead>
      <th>Entries</th>
      <th>Scores</th>
      <th></th>
    </thead>
    <% @pool.entries.sort_by{|e| -e.score }.each do |e| %>
      <tr>
        <td><%= e.name %></td>
        <td>
          <%= e.score %></td>
        </td>
        <td>
          <% if policy(e).show? %>
            <%= link_to 'View Entry', entry_path(id: e.id) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>