config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}

  root 'home#index'

  resources :award_ceremonies, only: :index
  resources :entries, only: [:show, :edit, :update]
  resources :pools, only: [:show, :index] do
    resources :entries, only: [:new, :create]
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :pool
  belongs_to :user
  has_many :picks, -> { order(:created_at) }, dependent: :destroy
  accepts_nested_attributes_for :picks
  validates_associated :picks

  delegate :award_ceremony, to: :pool
  delegate :email, to: :user
  delegate :award_ceremony_name, to: :pool
  delegate :locks_at, to: :pool

  def name
    email
  end

  def locked?
    Time.current >= locks_at
  end

  def score
    picks.map(&:nominee).select(&:winner?).count
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_action :authenticate_user!

  def new
    @entry = pool.entries.build(
      {
        picks_attributes: @pool.categories.map{ |c| Pick.new(category_id: c.id) }.map(&:attributes),
        user: current_user
      }
    )
  end

  def edit
    authorize entry
    entry
  end

  def show
    authorize entry
    entry
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update_attributes(entry_params)
      redirect_to @entry
    else
      render 'edit'
    end
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.pool = pool
    @entry.user = current_user
    if @entry.save
      redirect_to @entry
    else
      render 'new'
    end
  end

  private

  def entry
    @entry ||= Entry.joins(pool: { award_ceremony: :categories }).includes(:picks).find(params[:id])
  end

  def pool
    @pool ||= Pool.find(params[:pool_id])
  end

  def entry_params
    params
      .required(:entry)
      .permit(picks_attributes: [:id, :nominee_id, :category_id])
  end
end

app/views/entries/edit.html.erb
<div>
  <h2>Entry</h2>
  <h3><%= @entry.award_ceremony_name %></h3>
  <h3><%= @entry.email %></h3>

  <%= form_for(@entry) do |f| %>
    <fieldset>
      <ul class="entry">
        <%= f.fields_for :picks do |pf| %>
          <li class="category">
            <div><%= pf.object.category.name %></div>
              <ul>
                <% pf.object.category.nominees.each do |n| %>
                  <li class="nominee">
                    <%= label_tag "nominee-#{n.id}", n.name do %>
                      <%= pf.radio_button "nominee_id", n.id, { checked: pf.object.nominee_id == n.id, id: "nominee-#{n.id}" } %>
                      <%= n.name %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
          </li>
        <% end %>
      </ul>
    </fieldset>
    <%= submit_tag("Submit") %>
  <% end %>
</div>

app/views/entries/new.html.erb
<div>
  <h2>Entry</h2>
  <h3><%= @entry.award_ceremony_name %></h3>
  <h3><%= @entry.email %></h3>
  <%= form_for(@entry, url: pool_entries_path) do |f| %>
    <fieldset>
      <ul class="entry">
        <%= f.fields_for :picks, hidden_field_id: true do |pf| %>
          <li class="category">
            <%= pf.hidden_field :category_id, value: pf.object.category_id %>
            <div><%= pf.object.category.name %></div>
              <ul>
                <% pf.object.category.nominees.each do |n| %>
                  <li class="nominee">
                    <%= label_tag "nominee-#{n.id}", n.name do %>
                      <%= pf.radio_button "nominee_id", n.id, { checked: pf.object.nominee_id == n.id, id: "nominee-#{n.id}" } %>
                      <%= n.name %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
          </li>
        <% end %>
      </ul>
    </fieldset>
    <%= submit_tag("Submit") %>
  <% end %>
</div>

app/views/entries/show.html.erb
<div>
  <h2>Entry</h2>
  <h5><%= link_to @entry.award_ceremony_name, pool_path(@entry.pool) %></h5>
  <h5 class="entry-name-header"><%= @entry.email %></h5>
  <% if @entry.locked? %>
    <h5 class="entry-score-header">Score: <%= @entry.score %></h6>
  <% end %>

  <% if policy(@entry).edit?  %>
    <div>
      <%= link_to "Edit Entry", edit_entry_path(@entry) %>
    </div>
  <% end %>
  <table class="minimal-table entry">
    <thead>
      <th>Category</th>
      <th>Pick</th>
      <% if @entry.locked? %>
        <th>Winner</th>
      <% end %>
    </thead>
    <tbody>
      <% @entry.picks.each do |p| %>
        <tr class="category">
          <td>
            <%= p.category.name %>
          </td>
          <td>
            <% if p.nominee.present? %>
              <%= p.nominee.name %>
            <% end %>
          </td>
          <% if @entry.locked? %>
            <% if p.category.winner.present? %>
              <td class="<%= 'correct-winner' if p.nominee.winner? %>"><%= p.category.winner.name %></td>
            <% else %>
              <td>-</td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if @entry.locked? %>
    <h5 class="entry-score-footer">Score: <%= @entry.score %></h5>
  <% end %>
</div>